apiVersion: v1
kind: Service
metadata:
  name: service-my-node-app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: node-app
  type: LoadBalancer
